python train_kpcn.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd2/kbhan/KPCN \
    --model_name KPCN_manif_p12_full \
    --desc "KPCN_manif_p12_full" \
    --num_epoch 10 \
    --lr_dncnn 1e-6 \
    --manif_loss FMSE \
    --pnet_out_size 12 \
    --lr_pnet 1e-6 \
    --use_llpm_buf \
    --manif_learn \
    --w_manif 0.1 \
    --device_id 3 \
    --save 'weights_finetune' \
    --summary 'summary_finetune' \
    --start_epoch 4 \
    --best_err 3.077e-2