python train_kpcn.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd1/iycho/KPCN \
    --model_name KPCN_path_p12 \
    --desc "KPCN_path_p12" \
    --num_epoch 10 \
    --lr_dncnn 1e-4 \
    --pnet_out_size 12 \
    --lr_dncnn 1e-4 \
    --lr_pnet 1e-4 \
    --use_llpm_buf \
    --train_branches \
    --device_id 0