python train_adv.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd1/iycho/KPCN \
    --model_name KPCN_new_adv_2_leaky_refine \
    --desc "KPCN_new_adv_2_leaky_refine" \
    --num_epoch 20 \
    --lr_dncnn 2e-4 \
    --use_llpm_buf \
    --use_adv \
    --w_adv 0.0001 \
    --start_epoch 10 \
    --use_single \
    --device_id 2 \
    --activation "leaky_relu" \
    --use_krn