python train_adv.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd1/iycho/KPCN \
    --model_name KPCN_new_adv_2_sep \
    --desc "KPCN_new_adv_2_sep" \
    --num_epoch 10 \
    --lr_dncnn 1e-4 \
    --use_llpm_buf \
    --use_adv \
    --w_adv 0.0001 \
    --start_epoch 0 \
    --use_single \
    --separate \
    --device_id 1