python train_adv.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /home/kyubeom/ssd1/KPCN \
    --model_name ADV_GP \
    --desc "ADV_GP" \
    --num_epoch 10 \
    --lr_G_diffuse 1e-4 \
    --lr_G_specular 1e-4 \
    --lr_D 1e-4 \
    --use_llpm_buf \
    --manif_learn \
    --manif_loss FMSE \
    --pnet_out_size 12 \
    --lr_pnet 1e-4 \
    --w_manif 0.1 \
    --device_id 3 \
    --save "weights_adv"\
    --summary "summary_adv" \
    --num_epoch 15 \
    --start_epoch 9 \
    --lr_ckpt