python train_kpcn.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd2/kbhan/KPCN \
    --model_name KPCN_G_full_test \
    --desc "KPCN_G_full_test" \
    --train_branches \
    --num_epoch 10 \
    --lr_dncnn 1e-4 \
    --device_id 0 \
    --save "weights_test"\
    --summary "summary_test" \
    --num_epoch 10
