python train_ensemble.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd2/kbhan/KPCN \
    --model_name KPCN_ensemble_feature_full_2_sched \
    --desc "KPCN_ensemble_feature_full_2_sched" \
    --num_epoch 10 \
    --lr_dncnn 1e-4 \
    --use_llpm_buf \
    --lr_pnet 1e-4 \
    --manif_learn \
    --manif_loss FMSE \
    --pnet_out_size 12 \
    --w_manif 0.1 \
    --lr_inet 1e-4 \
    --device_id 3 \
    --save 'weights_ens_full' \
    --summary 'summary_ens_full' \
    --train_branches \
    --interpolate \
    --feature \
    --load