python train_adv.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd1/iycho/KPCN \
    --model_name KPCN_new_adv_2_2 \
    --desc "KPCN_new_adv_2_2" \
    --num_epoch 10 \
    --lr_dncnn 1e-4 \
    --use_llpm_buf \
    --use_adv \
    --w_adv 0.0001 \
    --start_epoch 6 \
    --use_single \
    --device_id 2