python train_kpcn.py \
    --single_gpu \
    --batch_size 8 \
    --val_epoch 1 \
    --data_dir /mnt/ssd2/kbhan/KPCN \
    --model_name KPCN_pbuf \
    --desc "KPCN_pbuf" \
    --num_epoch 10 \
    --lr_dncnn 1e-4 \
    --train_branches \
    --use_llpm_buf \
    --no_p_model \
    --device_id 3